ors:
  engine:
    source_file: /home/ors/files/mazowieckie-latest.osm.pbf
    graphs_root_path: /home/ors/graphs
    profiles:
      car:
        enabled: true
        profile: driving-car
        elevation: true
        encoder_options:
          turn_costs: true
          block_fords: false
          use_acceleration: true
      bike-regular:
        enabled: true
        profile: cycling-regular
        elevation: true
        encoder_options:
          consider_elevation: true
          turn_costs: true
          block_fords: false
      bike-road:
        enabled: true
        profile: cycling-road
        elevation: true
        encoder_options:
          consider_elevation: true
          turn_costs: true
          block_fords: false
      walking:
        enabled: true
        profile: foot-walking
        elevation: true
        encoder_options:
          block_fords: false

logging:
  level:
    root: WARN
    org.heigit: INFO
  file:
    name: /home/ors/logs/ors.log
