# Generated by Django 5.2.5 on 2025-09-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeStation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=9)),
                ('is_veturilo', models.BooleanField()),
                ('name', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VeturiloAloneBike',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=9)),
                ('name', models.CharField(max_length=32)),
                ('bike_number', models.CharField(max_length=8)),
                ('bike_type', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('state', models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VeturiloBikeStation',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=9)),
                ('name', models.CharField(max_length=128)),
                ('number', models.IntegerField()),
                ('available_bikes', models.IntegerField()),
            ],
        ),
    ]
