# Generated by Django 5.2.5 on 2025-09-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VeturiloAloneBike',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=9)),
                ('name', models.CharField(max_length=32)),
                ('number', models.CharField(max_length=8)),
                ('bike_type', models.IntegerField(choices=[(71, 'Default'), (183, 'Electric'), (228, 'Tandem')])),
                ('active', models.BooleanField()),
                ('state', models.CharField(max_length=16, null=True)),
                ('percentage', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Bikes_Veturilo_Alone_Bikes',
            },
        ),
        migrations.CreateModel(
            name='VeturiloStation',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=9)),
                ('name', models.CharField(max_length=128)),
                ('number', models.IntegerField()),
                ('bikes_available_to_rent', models.IntegerField()),
            ],
            options={
                'db_table': 'Bikes_Veturilo_Stations',
            },
        ),
    ]
