# Generated by Django 5.2.5 on 2025-09-27 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScooterCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'Bikes_Scooter_Companies',
            },
        ),
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('lat', models.DecimalField(decimal_places=15, max_digits=17)),
                ('lng', models.DecimalField(decimal_places=15, max_digits=17)),
                ('percentage', models.IntegerField()),
                ('distance_on_charge', models.IntegerField()),
                ('is_disabled', models.BooleanField(null=True)),
                ('last_reported', models.DateTimeField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bikes.scootercompany')),
            ],
            options={
                'db_table': 'Bikes_Scooters',
            },
        ),
    ]
