# Generated by Django 5.2.7 on 2025-10-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='street_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='stopstaging',
            name='street_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
