# Generated by Django 5.2.5 on 2025-09-05 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stoptime',
            old_name='stop_id',
            new_name='stop',
        ),
    ]
