# Generated by Django 5.2.5 on 2025-09-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='stop_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stop',
            name='stop_lon',
            field=models.FloatField(),
        ),
    ]
