# Generated by Django 5.2.7 on 2025-10-29 10:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasker', '0002_create_route_stops_mv'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteStopsMV',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('trip_id', models.CharField(max_length=64)),
                ('direction_id', models.IntegerField()),
                ('route_id', models.CharField(max_length=8)),
                ('stop_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), size=None)),
            ],
            options={
                'db_table': 'tasker_trip_stops',
                'managed': False,
            },
        ),
    ]
