# Generated by Django 5.2.7 on 2025-10-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasker', '0002_alter_stop_street_name_alter_stopstaging_street_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='stop_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='stopstaging',
            name='stop_name',
            field=models.CharField(max_length=64),
        ),
    ]
