# Generated by Django 5.2.5 on 2025-10-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasker', '0003_tripstopsmv_alter_calendardate_exception_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendardate',
            name='exception_type',
            field=models.IntegerField(choices=[(1, 'Added'), (2, 'Removed')]),
        ),
        migrations.AlterField(
            model_name='calendardatestaging',
            name='exception_type',
            field=models.IntegerField(choices=[(1, 'Added'), (2, 'Removed')]),
        ),
    ]
