# Generated by Django 5.2.7 on 2025-10-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasker', '0003_alter_stop_stop_name_alter_stopstaging_stop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='stop_name_stem',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='stopstaging',
            name='stop_name_stem',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
