# Generated by Django 5.2.7 on 2025-10-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasker', '0004_alter_stop_stop_name_stem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_headsign',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='tripstaging',
            name='trip_headsign',
            field=models.CharField(max_length=128),
        ),
    ]
