# Generated by Django 5.2.5 on 2025-11-09 09:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Trips', '0001_unlogged_tripstops'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripStops',
            fields=[
                ('trip_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('direction_id', models.IntegerField()),
                ('route_id', models.CharField(max_length=8)),
                ('stop_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), size=None)),
            ],
            options={
                'db_table': 'trips_TripStops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TripStopsStaging',
            fields=[
                ('trip_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('direction_id', models.IntegerField()),
                ('route_id', models.CharField(max_length=8)),
                ('stop_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), size=None)),
            ],
            options={
                'db_table': 'trips_TripStops_Staging',
                'managed': False,
            },
        ),
    ]
