# Generated by Django 5.2.5 on 2025-09-04 17:13

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tasker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopInfo',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Tasker.stop',),
        ),
    ]
